# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: python
before_install:
  - pip install Scrapy

script:
  - bash run.sh

# deploy
deploy:
  - provider: pages    # Deploy master to branch win-build
    skip-cleanup: true
    github-token: $GH_TOKEN  # Set in travis-ci.org dashboard
    keep-history: true
    local-dir: docs
    on:
      branch: master

