# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: required
cache: packages
dist: trusty
pandoc_version: 1.19.2.1
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python3-pip
  - sudo pip3 install virtualenv

script:
  - bash render-PTTdict.sh

# deploy
deploy:
  - provider: pages    # Deploy master to branch win-build
    skip-cleanup: true
    github-token: $GH_TOKEN  # Set in travis-ci.org dashboard
    keep-history: false
    local-dir: PTTdict/data/docs
    on:
      branch: master

