python:
  - "3.8"
sudo: false

branches:
  only:
    - master

install:
  - pip install Scrapy

cache:
  pip: true

script:
  - bash run.sh

# deploy
deploy:
  - provider: pages    # Deploy master to branch win-build
    target_branch: 'data'
    skip-cleanup: true
    github-token: $GH_TOKEN  # Set in travis-ci.org dashboard
    keep-history: true
    local-dir: docs
    on:
      branch: master

